name: Simple Infinite Runner Pygame

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python-version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pygame
    - name: Test on Linux
      run : |
        python -c "import os; os.environ['SDL_VIDEODRIVER'] = 'dummy'; exec(open('main.py').read())"
      if : matrix.os == 'ubuntu-latest'
    - name: Test on Windows
      run: |
        python main.py
      if : matrix.os == 'windows-latest'
    - name: Test on MacOS
      run: |
        python main.py
      if : matrix.os == 'macos-latest'
